BEGIN TRANSACTION;
DROP TABLE IF EXISTS "posts";
CREATE TABLE IF NOT EXISTS "posts" (
	"post_id"	INTEGER,
	"post_content"	TEXT,
	PRIMARY KEY("post_id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "votes";
CREATE TABLE IF NOT EXISTS "votes" (
	"post_id"	INTEGER NOT NULL,
	"username"	INTEGER NOT NULL,
	"rating"	INTEGER NOT NULL,
	PRIMARY KEY("post_id","username")
);
COMMIT;
